# Site settings
title: "Bacomathiques"
tagline: "Bacomathiques est un petit site web qui contient tout ce dont vous avez besoin pour réussir votre BAC de mathématiques en toute tranquillité : cours de mathématiques gratuits, téléchargeables et imprimables, annales et corrigés des sujets précédents, etc..."
url: "https://bacomathiqu.es"
repository: "Skyost/Bacomathiques"
timezone: "Europe/Paris"
includes_dir: ""

# Social
social:
  preview: "/assets/img/social.png"
  twitter: "Skyost_"
  googleplus: "Skyost"
  disqus: "bacomathiques"

# HTML Compresser
compress_html:
  clippings: "all"
  blanklines: true

# License
content_license:
  name: "Creative Commons BY-NC 4.0"
  full_name: "Licence Creative Commons Attribution - Pas d’Utilisation Commerciale 4.0 International"
  acronym: "CC BY NC"
  url: "https://creativecommons.org/licenses/by-nc/4.0/deed.fr"
  image: "/assets/img/license.svg"

# SASS options
sass:
  sass_dir: "_sass"
  style: "compressed"

# Production
exclude: [".scss", "README.md", "CNAME"]

# Gems
plugins: ["jekyll-redirect-from"]