# Site settings
title: "Bacomathiques"
tagline: "Bacomathiques est un petit site web qui contient tout ce que vous avez besoin pour réussir votre BAC de mathématiques en toute tranquillité : cours de mathématiques gratuits, téléchargeables et imprimables, annales et corrigés des sujets précédents, etc..."
url: "https://bacomathiqu.es"

# Social
social:
  preview: "/assets/img/social.png"
  twitter: "Skyost_"
  googleplus: "Skyost"
  github: "Skyost"
  disqus: "bacomathiques"

# HTML Compresser
compress_html:
  clippings: all
  blanklines: true
  
content_license:
  name: "Creative Commons BY-NC 4.0"
  acronym: "CC BY NC"
  image: "/assets/img/lessons/license.svg"
  url: "https://creativecommons.org/licenses/by-nc/4.0/deed.fr"

# SASS options
sass:
  sass_dir: _sass
  style: compressed

# Production
exclude: [".scss", "README.md"]