include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_single_quotes

analyzer:
  errors:
    omit_local_variable_types: ignore
    use_key_in_widget_constructors: ignore