name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 2.0.0+38
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  http: ^0.13.0
  url_launcher: ^5.4.11
  catcher: ^0.5.0
  flutter_svg: ^0.19.3
  share: ^2.0.1
  rate_my_app: ^1.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3
  pedantic: ^1.11.0
  provider: ^5.0.0
  day_night_switcher: ^0.2.0
  flutter_layout_grid: ^0.11.6
  google_fonts: ^2.0.0
  collection: ^1.15.0
  app_tracking_transparency: ^1.1.0
  google_mobile_ads: ^0.11.0
  flutter_widget_from_html_core: ^0.5.2
  flutter_tex_js: ^1.2.0
  flutter_math:
    git:
      url: https://github.com/Skyost/flutter_math
      ref: master
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - google_fonts/
