name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 2.1.2+46
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.0.20
  catcher: ^0.6.9
  flutter_svg: ^1.0.3
  share_plus: ^3.1.0
  rate_my_app: ^1.1.2
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  day_night_switcher: ^0.2.0
  flutter_layout_grid: ^1.0.6
  google_fonts: ^2.3.1
  collection: ^1.15.0
  flutter_widget_from_html_core: ^0.8.5
  fwfh_svg: ^0.7.2
  flutter_math_fork: ^0.6.1
  indexed_list_view: ^2.0.1
  google_mobile_ads: ^1.1.0
  app_tracking_transparency: ^2.0.2
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - google_fonts/
