name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 2.0.0-beta.2+39
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  http: ^0.13.0
  url_launcher: ^6.0.2
  catcher: ^0.6.1
  flutter_svg: ^0.21.0-nullsafety.0
  share: ^2.0.1
  rate_my_app: ^1.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.4
  pedantic: ^1.11.0
  provider: ^5.0.0
  day_night_switcher: ^0.2.0
  flutter_layout_grid: ^1.0.0-nullsafety.6
  google_fonts: ^2.0.0
  collection: ^1.15.0
  admob_flutter: ^2.0.0-nullsafety.0
  flutter_widget_from_html_core: ^0.6.0-rc.2021031201
  fwfh_svg: ^0.6.0-rc.2021031201
  flutter_math_fork: ^0.3.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - google_fonts/
