name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 2.0.3+44
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  http: ^0.13.4
  url_launcher: ^6.0.18
  catcher: ^0.6.9
  flutter_svg: ^1.0.3
  share_plus: ^3.0.4
  rate_my_app: ^1.1.1
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  day_night_switcher: ^0.2.0
  flutter_layout_grid: ^1.0.3
  google_fonts: ^2.2.0
  collection: ^1.15.0
  flutter_widget_from_html_core: ^0.8.4
  fwfh_svg: ^0.7.2
  flutter_math_fork: ^0.6.1
  indexed_list_view: ^2.0.1
  google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2
  fwfh_text_style: ^2.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - google_fonts/
