name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 2.2.1+49
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  share_plus: ^7.2.1
  rate_my_app: ^2.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  day_night_switcher: ^0.2.0+1
  flutter_layout_grid: ^2.0.5
  google_fonts: ^6.1.0
  collection: ^1.18.0
  flutter_widget_from_html_core: ^0.14.9
  fwfh_svg: ^0.8.0+4
  flutter_math_fork: ^0.7.2
  indexed_list_view: ^3.0.1
  google_mobile_ads: ^4.0.0
  flutter_riverpod: ^2.4.9
  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - google_fonts/
