name: bacomathiques
description: Cours de mathématiques gratuits pour réviser le BAC !
version: 1.1.0+26

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  webview_flutter: ^0.3.19
  mime: ^0.9.6
  flutter_html: ^0.11.1
  url_launcher: ^5.4.1
  flutter_svg: ^0.17.1
  firebase_admob: ^0.9.0
  share: ^0.6.3
  flutter_statusbarcolor: ^0.2.3
  transparent_image: ^1.0.0
  rate_my_app: ^0.5.0
  path_provider: ^1.6.0
  shared_preferences: ^0.5.6
  pedantic: ^1.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/fonts/
  - assets/images/
  - assets/webview/
  - assets/webview/css/
  - assets/webview/css/bootstrap/
  - assets/webview/js/
  - assets/webview/js/anchor/
  - assets/webview/js/jquery/
  - assets/webview/js/mathjax/
  - assets/webview/js/mathjax/es5/
  - assets/webview/js/mathjax/es5/a11y/
  - assets/webview/js/mathjax/es5/adaptors/
  - assets/webview/js/mathjax/es5/input/
  - assets/webview/js/mathjax/es5/input/tex/
  - assets/webview/js/mathjax/es5/input/tex/extensions/
  - assets/webview/js/mathjax/es5/output/
  - assets/webview/js/mathjax/es5/output/chtml/
  - assets/webview/js/mathjax/es5/output/chtml/fonts/
  - assets/webview/js/mathjax/es5/output/chtml/fonts/woff-v2/
  - assets/webview/js/mathjax/es5/sre/
  - assets/webview/js/mathjax/es5/sre/mathmaps/
  - assets/webview/js/mathjax/es5/sre/mathmaps/en/
  - assets/webview/js/mathjax/es5/sre/mathmaps/en/functions/
  - assets/webview/js/mathjax/es5/sre/mathmaps/en/symbols/
  - assets/webview/js/mathjax/es5/sre/mathmaps/en/units/
  - assets/webview/js/mathjax/es5/sre/mathmaps/es/
  - assets/webview/js/mathjax/es5/sre/mathmaps/es/functions/
  - assets/webview/js/mathjax/es5/sre/mathmaps/es/symbols/
  - assets/webview/js/mathjax/es5/sre/mathmaps/es/units/
  - assets/webview/js/mathjax/es5/sre/mathmaps/fr/
  - assets/webview/js/mathjax/es5/sre/mathmaps/fr/functions/
  - assets/webview/js/mathjax/es5/sre/mathmaps/fr/symbols/
  - assets/webview/js/mathjax/es5/sre/mathmaps/fr/units/
  - assets/webview/js/mathjax/es5/sre/mathmaps/nemeth/
  - assets/webview/js/mathjax/es5/sre/mathmaps/nemeth/functions/
  - assets/webview/js/mathjax/es5/sre/mathmaps/nemeth/symbols/
  - assets/webview/js/mathjax/es5/sre/mathmaps/nemeth/units/
  - assets/webview/js/mathjax/es5/ui/
  fonts:
  - family: handlee-regular
    fonts:
    - asset: assets/fonts/handlee-regular.ttf

flutter_native_splash:
  image: assets/images/splash.png
  color: "3498DB"